# Generated by Django 3.0.8 on 2020-07-28 07:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug_submit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='bug_inform',
        ),
        migrations.RenameModel(
            old_name='Topic',
            new_name='bug_type',
        ),
        migrations.AlterModelOptions(
            name='bug_inform',
            options={'verbose_name_plural': 'bug_informs'},
        ),
    ]
