# Generated by Django 3.0.8 on 2020-07-29 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug_submit', '0002_auto_20200728_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug_inform',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='bug_type',
            name='bug_owner',
        ),
        migrations.AddField(
            model_name='bug_inform',
            name='bug_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bug_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
