# Generated by Django 3.0.8 on 2020-07-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_submit', '0003_auto_20200729_0935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bug_type',
        ),
        migrations.AlterModelOptions(
            name='bug_inform',
            options={},
        ),
    ]
