# Generated by Django 3.0.8 on 2020-08-06 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug_submit', '0004_auto_20200729_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug_inform',
            options={'verbose_name_plural': 'bug_informs'},
        ),
        migrations.AlterField(
            model_name='bug_inform',
            name='bug_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
