# Generated by Django 3.0.8 on 2020-07-10 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0002_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
