# Generated by Django 3.0.8 on 2020-08-06 08:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0006_auto_20200806_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='data'),
        ),
    ]
